# Generated by Django 2.0.3 on 2018-05-12 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acilis_kapanis_saati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pazartesi_acilis', models.TimeField()),
                ('pazartesi_kapanis', models.TimeField()),
                ('sali_acilis', models.TimeField()),
                ('sali_kapanis', models.TimeField()),
                ('carsamba_acilis', models.TimeField()),
                ('carsamba_kapanis', models.TimeField()),
                ('persembe_acilis', models.TimeField()),
                ('persembe_kapanis', models.TimeField()),
                ('cuma_acilis', models.TimeField()),
                ('cuma_kapanis', models.TimeField()),
                ('cumartesi_acilis', models.TimeField()),
                ('cumartesi_kapanis', models.TimeField()),
                ('pazar_acilis', models.TimeField()),
                ('pazar_kapanis', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Odeme_sekilleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_sekli', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Oyuncu_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Oyuncu_fotolari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Oyuncu_tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oyuncular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=60)),
                ('adi', models.CharField(max_length=60)),
                ('soyadi', models.CharField(max_length=60)),
                ('dogum_tarihi', models.DateField()),
                ('kayit_tarihi', models.DateTimeField()),
                ('aktif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oyunlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayit_zamani', models.DateTimeField()),
                ('oyun_saati', models.DateTimeField()),
                ('odeme', models.BooleanField()),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Oyuncular')),
            ],
        ),
        migrations.CreateModel(
            name='Saha_fotolari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Saha_yoneticileri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=60)),
                ('adi', models.CharField(max_length=60)),
                ('soyadi', models.CharField(max_length=60)),
                ('dogum_tarihi', models.DateField()),
                ('kayit_tarihi', models.DateTimeField()),
                ('degerlendirme', models.IntegerField()),
                ('aktif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Saha_yoneticisi_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('saha_yoneticisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Saha_yoneticileri')),
            ],
        ),
        migrations.CreateModel(
            name='Saha_yoneticisi_tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
                ('saha_yoneticisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Saha_yoneticileri')),
            ],
        ),
        migrations.CreateModel(
            name='Sahalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=60)),
                ('ucreti', models.DecimalField(decimal_places=2, max_digits=7)),
                ('minibus', models.BooleanField()),
                ('kayit_tarihi', models.DateField()),
                ('degerlendirme', models.IntegerField()),
                ('odeme_sekli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Odeme_sekilleri')),
                ('saha_yoneticisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Saha_yoneticileri')),
            ],
        ),
        migrations.AddField(
            model_name='saha_fotolari',
            name='saha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Sahalar'),
        ),
        migrations.AddField(
            model_name='oyunlar',
            name='saha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Sahalar'),
        ),
        migrations.AddField(
            model_name='oyuncu_tel',
            name='oyuncu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Oyuncular'),
        ),
        migrations.AddField(
            model_name='oyuncu_fotolari',
            name='oyuncu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Oyuncular'),
        ),
        migrations.AddField(
            model_name='oyuncu_email',
            name='oyuncu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahaapp.Oyuncular'),
        ),
    ]
